### ISSUE TITLE
API endpoint update for AddTag

### ISSUE THREAD

**Issue by hyunbin7303** [hyunbin7303/HBlog#55]
## Current implementation
* Http Verb : PUT
* Url : `api/posts/{postid}/AddTag` 

### For the API side
* Http Verb : POST
* Url : `api/posts/{postid}/Tags`

### Frontend Side
Need to change the url for adding a tag for the post.

**Comment by SamTheKorean** [comment]
So basically it needs to add multiple tags?

**Comment by hyunbin7303** [comment]
Merged into dev/master branch. Closing this ticket.
