### ISSUE TITLE
Frontend | Display posts for the specific tags

### ISSUE THREAD

**Issue by hyunbin7303** [hyunbin7303/HBlog#61]
![Image](https://github.com/user-attachments/assets/ea30bb5a-2e7c-4957-b262-cdf073b06a45)

## Requirements

- [ ] When user clicks the `Apply` button after clicking all tags, user should only see the corresponding blog posts.

**Comment by hyunbin7303** [comment]
@habbs19 Created this ticket for fixing tag feature.
Having said that, backend side is not completed yet I believe. 
If API won't work, please tag `blocked` in the label.

**Comment by habbs19** [comment]
i noticed the backend is already implemented. You get GetPosts with QueryParam module. we can pass in the TagIds and it will filter

**Comment by hyunbin7303** [comment]
@habbs19  Agree. Closing this ticket.
